# Header_1
## Header_2
### Header_3
#### Header_4
##### Header_5

Абзацы создаются при помощи пустой строки. Если вокруг текста сверху и снизу есть пустые строки, то текст превращается в абзац.

Чтобы сделать перенос строки вместо абзаца,
нужно поставить два пробела в конце предыдущей строки.

Заголовки отмечаются диезом # в начале строки, от одного до шести. например:

# Заголовок первого уровня
##
###

### Списки

- первый
- второй
- третий

* элемент 1
* элемент 2
    * элемент 2.1
    * элемент 2.2


1. элемент
2. элемент
    1. вложенный элемент
    2. вложенный элемент
3. элемент
4. Какой-то текст, который необходим для нарабатывания навыков

In [233]:
import numpy as np

In [234]:
vec = np.array([1,2,3])
vec.ndim # количество осей

1

In [235]:
mat = np.array([[1,2,3],[4,5,6]])
mat.ndim

2

In [236]:
vec.shape

(3,)

In [237]:
mat.dtype.name

'int64'

In [238]:
mat.itemsize

8

In [239]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [240]:
B = np.array([(1,2,3),(4,5,6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [241]:
np.zeros((3,))

array([0., 0., 0.])

In [242]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [243]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [244]:
np.empty((2,5))

array([[6.93886257e-310, 6.93886257e-310, 6.93887403e-310,
        6.93887403e-310, 6.93887403e-310],
       [6.93887403e-310, 6.93887403e-310, 6.93887403e-310,
        6.93887403e-310, 6.93887403e-310]])

In [245]:
np.arange(2,20,3) # аналогично стандартной функции range python, правая граница не включается

array([ 2,  5,  8, 11, 14, 17])

In [246]:
np.arange(2.5,8.7,0.9) # но может работать и с вещественными числами

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [247]:
np.linspace(2,18,14) # правая граница включается (по умолчанию)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [248]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [249]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [250]:
C = np.arange(6).reshape(2,-1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [251]:
C.T # транспонирование массива

array([[0, 3],
       [1, 4],
       [2, 5]])

In [252]:
 # объединение массивов по заданной оси
A = np.arange(6).reshape(2,-1)
np.hstack((A,A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [253]:
np.vstack((A,A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [254]:
np.concatenate((A,A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [255]:
# повторение существующего массива
a = np.arange(3)
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [256]:
np.tile(a,(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [257]:
# Базовые операции
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

In [258]:
print (A)
print (B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [259]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [260]:
A * 1.0 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [261]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [262]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [263]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [264]:
A * B # поэлементное умножение

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [265]:
A.dot(B) # матричное умножение

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [266]:
np.tile(np.arange(0,40,10),(3,1)).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [267]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [268]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [269]:
A.min()

0

In [270]:
A.max(axis = 0)

array([6, 7, 8])

In [271]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [272]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
a[2:5]

array([2, 3, 4])

In [274]:
a[3:8:2]

array([3, 5, 7])

In [275]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [276]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [277]:
A[:,2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [278]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [279]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [280]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [281]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [282]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [283]:
A[np.logical_and(A != 7, A % 5 != 3)] # также можно использовать логические операции

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [284]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [285]:
start = time.clock()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.clock()-start) # время выполнения в секудах

0.39290699999999923


In [286]:
start = time.clock()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.clock() - start)

0.2951599999999992


In [287]:
start = time.clock()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.clock() - start)

0.005452000000000012


In [288]:
start = time.clock()
ans = A_quick_arr.dot(B_quick_arr)
print(time.clock() - start)

0.0074710000000006715


In [289]:
import pandas as pd
my_series = pd.Series([5,6,7,8,9,10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [290]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [291]:
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [292]:
my_series[4]

9

In [293]:
my_series2 = pd.Series([5,6,7,8,9,10], index = ['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [294]:
my_series2[['a','b','f']]

a     5
b     6
f    10
dtype: int64

In [295]:
my_series2[['a','b','f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [296]:
my_series2[my_series2 > 0] * 2

c    14
d    16
e    18
dtype: int64

In [297]:
my_series3 = pd.Series({'a':5, 'b':6, 'c':7, 'd':8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [298]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [299]:
my_series3.index = ['A','B','C','D']
my_series3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

In [300]:
df = pd.DataFrame({
...    'country':['Kazakhstan','Russia','Belarus','Ukraine'],
...    'population':[17.04,143.5,9.5,45.5],    
...    'square' :[2724902,17125191,207600,603628]
... }) 
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [301]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [302]:
df.columns


Index(['country', 'population', 'square'], dtype='object')

In [303]:
df.index


RangeIndex(start=0, stop=4, step=1)

In [304]:
df = pd.DataFrame({
...    'country':['Kazakhstan','Russia','Belarus','Ukraine'],
...    'population':[17.04,143.5,9.5,45.5],    
...    'square' :[2724902,17125191,207600,603628]
... }, index = ['KZ', 'RU', 'BY', 'UK']) 
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UK     Ukraine       45.50    603628

In [305]:
df.index = ['KZ', 'RU', 'BY', 'UK']
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UK               Ukraine       45.50    603628

In [306]:
df['country']

Country Code
KZ    Kazakhstan
RU        Russia
BY       Belarus
UK       Ukraine
Name: country, dtype: object

In [307]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [308]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [309]:
df.loc[['KZ', 'RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [310]:
df.loc['KZ':'BY', :]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [311]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UK               Ukraine    603628

In [312]:
df.reset_index()

Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UK     Ukraine       45.50    603628

In [313]:
df['density'] = df['population'] / df['square']
df

country  population    square   density
Country Code                                            
KZ            Kazakhstan       17.04   2724902  0.000006
RU                Russia      143.50  17125191  0.000008
BY               Belarus        9.50    207600  0.000046
UK               Ukraine       45.50    603628  0.000075

In [314]:
df.drop(['density'], axis = 'columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UK               Ukraine       45.50    603628

In [315]:
df = df.rename(columns = {'Contry Code' : 'contry_code'})
df

country  population    square   density
Country Code                                            
KZ            Kazakhstan       17.04   2724902  0.000006
RU                Russia      143.50  17125191  0.000008
BY               Belarus        9.50    207600  0.000046
UK               Ukraine       45.50    603628  0.000075

In [316]:
titanic_df = pd.read_csv('train.csv')
print(titanic_df.head())

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [317]:
print(titanic_df.groupby(['Sex', 'Survived'])['PassengerId'].count())

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: PassengerId, dtype: int64


In [318]:
print(titanic_df.groupby(['Pclass', 'Survived'])['PassengerId'].count())

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: PassengerId, dtype: int64


In [319]:
import pandas as pd
%matplotlib inline

In [320]:
pass_data = pd.read_csv('train.csv')
pass_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [321]:
pass_data.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [322]:
pass_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [323]:
pass_data[2:5]

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
2                        Heikkinen, Miss. Laina  female  26.0      0      0   
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   

             Ticket    Fare Cabin Embarked  
2  STON/O2. 3101282   7.925   NaN        S  
3            113803  53.100  C123        S  
4            373450   8.050   NaN        S

In [324]:
pass_data.iloc [1:5,1:3]

Survived  Pclass
1         1       1
2         1       3
3         1       1
4         0       3

In [325]:
pass_data['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [326]:
pass_data[['Name', 'Sex', 'Parch']].head()

Name     Sex  Parch
0                            Braund, Mr. Owen Harris    male      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      0
2                             Heikkinen, Miss. Laina  female      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      0
4                           Allen, Mr. William Henry    male      0

In [327]:
pass_data[pass_data['Sex'] == 'female'].head()#женщины на борту

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [328]:
#женщины старше 60 и мужчины на борту
pass_data[(pass_data['Sex'] == 'female') & (pass_data['Age'] >=60) | (pass_data['Sex'] == 'male')].head()

PassengerId  Survived  Pclass                            Name   Sex   Age  \
0            1         0       3         Braund, Mr. Owen Harris  male  22.0   
4            5         0       3        Allen, Mr. William Henry  male  35.0   
5            6         0       3                Moran, Mr. James  male   NaN   
6            7         0       1         McCarthy, Mr. Timothy J  male  54.0   
7            8         0       3  Palsson, Master. Gosta Leonard  male   2.0   

   SibSp  Parch     Ticket     Fare Cabin Embarked  
0      1      0  A/5 21171   7.2500   NaN        S  
4      0      0     373450   8.0500   NaN        S  
5      0      0     330877   8.4583   NaN        Q  
6      0      0      17463  51.8625   E46        S  
7      3      1     349909  21.0750   NaN        S

In [329]:
pass_data[(pass_data.Sex == 'female') & 
          (pass_data.Age > 18) & 
          (pass_data.Age < 25) & 
          (pass_data.SibSp == 0) & (pass_data.Parch == 0)].shape

(25, 12)

In [330]:
pass_data.Age.hist(bins = 30)

In [331]:
pass_data.rename(columns = {'Sex': 'Sex'}, inplace =True)
pass_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [332]:
def get_last_name(name):
    return name.split(',')[0].strip()

last_names = pass_data['Name'].apply(get_last_name)
last_names.head()

0       Braund
1      Cumings
2    Heikkinen
3     Futrelle
4        Allen
Name: Name, dtype: object

In [333]:
pass_data['last_name'] = last_names
pass_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  last_name  
0      0         A/5 21171   7.2500   NaN        S     Braund  
1      0          PC 17599  71.2833   C85        C    Cumings  
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      0            113803  53.1000  C123        S   Futrelle  
4      0            373450   8.0500   NaN        S      Allen

In [334]:
pass_data.drop('last_name', axis=1, inplace =True)
pass_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [335]:
pass_data['Age'].isnull().head()

0    False
1    False
2    False
3    False
4    False
Name: Age, dtype: bool

In [336]:
pass_data[pass_data['Cabin'].notnull()].head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [337]:
pass_data.sort_values(by = ['Pclass', 'Fare'], ascending = True).head()

PassengerId  Survived  Pclass                             Name   Sex  \
263          264         0       1            Harrison, Mr. William  male   
633          634         0       1    Parr, Mr. William Henry Marsh  male   
806          807         0       1           Andrews, Mr. Thomas Jr  male   
815          816         0       1                 Fry, Mr. Richard  male   
822          823         0       1  Reuchlin, Jonkheer. John George  male   

      Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
263  40.0      0      0  112059   0.0   B94        S  
633   NaN      0      0  112052   0.0   NaN        S  
806  39.0      0      0  112050   0.0   A36        S  
815   NaN      0      0  112058   0.0  B102        S  
822  38.0      0      0   19972   0.0   NaN        S

In [338]:
pass_data.sort_values(by = ['Pclass', 'Fare'], ascending = [True, False]).head()

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   
27            28         0       1      Fortune, Mr. Charles Alexander   
88            89         1       1          Fortune, Miss. Mabel Helen   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C  
27     male  19.0      3      2     19950  263.0000  C23 C25 C27        S  
88   female  23.0      3      2     19950  263.0000  C23 C25 C27        S

In [339]:
pass_data.groupby('Sex')

In [340]:
pass_data.groupby('Sex')['Pclass'].value_counts()

Sex     Pclass
female  3         144
        1          94
        2          76
male    3         347
        1         122
        2         108
Name: Pclass, dtype: int64

In [341]:
pass_data.groupby('Pclass')['Fare'].describe()

count       mean        std  min       25%      50%   75%       max
Pclass                                                                     
1       216.0  84.154687  78.380373  0.0  30.92395  60.2875  93.5  512.3292
2       184.0  20.662183  13.417399  0.0  13.00000  14.2500  26.0   73.5000
3       491.0  13.675550  11.778142  0.0   7.75000   8.0500  15.5   69.5500

In [342]:
pass_data.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [343]:
pass_data.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [344]:
pass_data.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [345]:
pass_data.groupby('Sex', as_index = False)['Survived'].mean()


Sex  Survived
0  female  0.742038
1    male  0.188908