# 1 #  
## 2  
### 3  
##### 4
# 5  

- 1  
- 2 
- 3  
  
* 1  
* 2
    * 3
        * 4
        
    







1. el  
2. el
    1. el  
    2. el  
3. el    

>  This is a header.

[~~1~~](//google.com)

**1**

***2***

[1]: //placehold.it/250*100 

![1](//placehold.it/150x100)

In [11]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
import numpy as np
a = np.array([1,2,3])
a.ndim

1

In [ ]:
import numpy as np
a = np.array([[1,2,3], [2,3,4]])
a.ndim

In [2]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.arange(1,51,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [4]:
a = np.arange(20).reshape(2,-1).T
a

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [5]:
a = np.arange(20).reshape(2,-1).T
print (a)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [6]:
a = np.arange(20).reshape(2,-1)
b = np.arange(20).reshape(2,-1)
a+b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [7]:
a = np.arange(20).reshape(2,-1)
a**4

array([[     0,      1,     16,     81,    256,    625,   1296,   2401,
          4096,   6561],
       [ 10000,  14641,  20736,  28561,  38416,  50625,  65536,  83521,
        104976, 130321]], dtype=int32)

In [8]:

a = np.arange(20).reshape(2,-1)
b = np.arange(20).reshape(-1,2)
a.dot(b)


array([[ 570,  615],
       [1470, 1615]])

In [9]:
np.tile(np.arange(0,49,10),(3,1)).T+np.array([1,2,3])

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [11]:
np.exp(a)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
        6.56599691e+07, 1.78482301e+08]])

In [12]:
a.min()

0

In [13]:
a.max(axis=0)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
a.max(axis=1)

array([ 9, 19])

In [15]:
a.sum(axis=0)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
a.sum(axis=1)

array([ 45, 145])

In [17]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[1:5]

array([1, 2, 3, 4])

In [19]:
a[2:10:2]

array([2, 4, 6, 8])

In [21]:
a=np.arange(100).reshape(10,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
a[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [23]:
a[:,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [24]:
a[2:5,5:10]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [25]:
a[-1,-1]

99

In [26]:
a[[2,8,4],[5,6,0]]

array([25, 86, 40])

In [29]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[a%3!=2]

array([0, 1, 3, 4, 6, 7, 9])

In [31]:
a[np.logical_and(a!=9,a%3!=2)]

array([0, 1, 3, 4, 6, 7])

In [34]:
import time

a_quick_arr=np.random.normal(size=(1000000,))
b_quick_arr=np.random.normal(size=(1000000,))

a_slow_list, b_slow_list=list(a_quick_arr), list(b_quick_arr)

In [41]:
start=time.clock()
ans=0
for i in range(len(a_slow_list)):
    ans += a_slow_list[i] * b_slow_list[i]
print(time.clock() - start)

0.05156247060045871


In [47]:
start = time.clock()
ans = np.sum(a_quick_arr*b_quick_arr)
print(time.clock() - start)

0.0015114117056782561


In [48]:
start = time.clock()
ans = a_quick_arr.dot(b_quick_arr)
print(time.clock() - start)

0.0006667590345159624


In [49]:
import pandas as pd
my_series=pd.Series([5,6,7,8,9,10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [50]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [51]:
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [52]:
my_series[4]

9

In [60]:
my_series2=pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])
my_series2['a']

5

In [61]:
my_series2[['a','b','f']]

a     5
b     6
f    10
dtype: int64

In [62]:
my_series2[['a','b','f']]=0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [63]:
my_series2[my_series2>1]

c    7
d    8
e    9
dtype: int64

In [64]:
my_series2[my_series2>1]*2

c    14
d    16
e    18
dtype: int64

In [65]:
my_series3=pd.Series({'a':5,'b':6,'c':7})
my_series3

a    5
b    6
c    7
dtype: int64

In [66]:
my_series3.name='numbers'
my_series3.index.name='letters'
my_series3

letters
a    5
b    6
c    7
Name: numbers, dtype: int64

In [67]:
my_series3.index=['A','B','C']
my_series3

A    5
B    6
C    7
Name: numbers, dtype: int64

In [71]:
df=pd.DataFrame({
...   'country': ['Russia','Belarus','Kazakhstan','Ukraine' ],
...   'population':[143.5, 9.5, 17.04, 45.5],
...   'square':[17125191,207600,2724902,603628]     
... })
df

country  population    square
0      Russia      143.50  17125191
1     Belarus        9.50    207600
2  Kazakhstan       17.04   2724902
3     Ukraine       45.50    603628

In [75]:
df['country']

0        Russia
1       Belarus
2    Kazakhstan
3       Ukraine
Name: country, dtype: object

In [77]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [79]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [81]:
df=pd.DataFrame({
...   'country': ['Russia','Belarus','Kazakhstan','Ukraine' ],
...   'population':[143.5, 9.5, 17.04, 45.5],
...   'square':[17125191,207600,2724902,603628]     
... }, index=['RU','BY','KZ','UA'])
df

country  population    square
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
KZ  Kazakhstan       17.04   2724902
UA     Ukraine       45.50    603628

In [84]:
df['country']

RU        Russia
BY       Belarus
KZ    Kazakhstan
UA       Ukraine
Name: country, dtype: object

In [86]:
df.loc['RU']

country         Russia
population       143.5
square        17125191
Name: RU, dtype: object

In [88]:
df.iloc[0]

country         Russia
population       143.5
square        17125191
Name: RU, dtype: object

In [91]:
df.loc['RU':'BY',:]

country  population    square
RU   Russia       143.5  17125191
BY  Belarus         9.5    207600

In [93]:
df[df.population>20][['country']]

country
RU   Russia
UA  Ukraine

In [95]:
df.reset_index()

index     country  population    square
0    RU      Russia      143.50  17125191
1    BY     Belarus        9.50    207600
2    KZ  Kazakhstan       17.04   2724902
3    UA     Ukraine       45.50    603628

In [98]:
df['density']=df['population']/df['square']*1000000
df

country  population    square    density
RU      Russia      143.50  17125191   8.379469
BY     Belarus        9.50    207600  45.761079
KZ  Kazakhstan       17.04   2724902   6.253436
UA     Ukraine       45.50    603628  75.377550

In [101]:
df.drop(['density'], axis='columns')

country  population    square
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
KZ  Kazakhstan       17.04   2724902
UA     Ukraine       45.50    603628

In [104]:
df.index=['RU','BY','KZ','UA']
df.index.name='Country Code'
df

country  population    square    density
Country Code                                             
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
KZ            Kazakhstan       17.04   2724902   6.253436
UA               Ukraine       45.50    603628  75.377550

In [106]:
df=df.rename(columns={'County Code': ' country_code'})
df

country  population    square    density
Country Code                                             
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
KZ            Kazakhstan       17.04   2724902   6.253436
UA               Ukraine       45.50    603628  75.377550