# Markdown

## Краткое руководство

# 1 level #
## 2 level
### 3 level
#### 4 level
##### 5 level
###### 6 level



In [3]:
- el 1
- el 2
- el 3

SyntaxError: invalid syntax (<ipython-input-3-4d0682c4788c>, line 1)

- el 1
- el 2
- el 3


* el 1
* el 2
    * el 2.1
* el 3

1. el 1
2. el 2
    1. el 2.1
    2. el 2.2
    

> Hallo

***


[link](http://example.com/link "I'm ur Daddy")

![Alt text](//placehold.it/150*100 "Text")

In [1]:
import numpy as np

In [5]:
vec = np.array([1,2,3])
vec.ndim

1

In [7]:
vec.shape


(3,)

In [9]:
mat = np.array([[1,2,3], [4,5,6]])
mat.ndim

2

In [10]:
mat.itemsize

4

In [11]:
mat.dtype.name

'int32'

In [12]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [13]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [14]:
B = np.array([(1,2,3), (4,5,6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.arange( 2, 20 , 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(8).reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
C = np.arange(9).reshape(3,3)
C.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [20]:
np.hstack((C, C*2))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [21]:
np.concatenate((C, C**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25],
       [ 6,  7,  8, 36, 49, 64]])

In [24]:
print(C)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]]


In [25]:
 A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
A+B

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [28]:
3*A


array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [29]:
A.dot(B)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [30]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [6]:
B = np.arange(9).reshape(3,3)
B.min()

0

In [7]:
B.max(axis = 0)

array([6, 7, 8])

In [8]:
B.sum(axis = 0)

array([ 9, 12, 15])

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[2:5]

array([2, 3, 4])

In [15]:
a[3:8:2]

array([3, 5, 7])

In [18]:
A = np.arange(100).reshape(10,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
A[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [21]:
A[:, 2:5]

array([[ 2,  3,  4],
       [12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [22]:
A[5,4:6]

array([54, 55])

In [23]:
A[-1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
A[[4,7,9],[5,0,9]]

array([45, 70, 99])

In [26]:
C = np.arange(10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
C[C % 5!= 3]

array([0, 1, 2, 4, 5, 6, 7, 9])

In [36]:
import time

A_quick_arr = np.random.normal(size = (100000,))
B_quick_arr = np.random.normal(size = (100000,))

A_slow_list, B_slow_list = list(A_quick_arr),list(B_quick_arr)

In [37]:
start = time.clock()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.clock() - start)    

0.06115886300005968


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """


In [38]:
start = time.clock()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(100000)])
print(time.clock() - start)

0.03405225500000597


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [40]:
start = time.clock()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.clock() - start)

0.001359160999982123


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [41]:
start = time.clock()
ans = A_quick_arr.dot(B_quick_arr)
print(time.clock() - start)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


0.22489903800010325


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [45]:
import pandas as pd
my = pd.Series([5,6,7,8,9,10])
my

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [46]:
my.index

RangeIndex(start=0, stop=6, step=1)

In [48]:
my.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [50]:
my[2]

7

In [56]:
my2 = pd.Series([5, 6, 7, 8 ,9, 10], index=['a','b','c','d','e','f'])
my2['c']


7

In [54]:
my2[['a','c','e']]

a    5
c    7
e    9
dtype: int64

In [58]:
my2[['a','c','e']] = 0
my2

a     0
b     6
c     0
d     8
e     0
f    10
dtype: int64

In [61]:
my2[my2 > 0]* 2


b    12
d    16
f    20
dtype: int64

In [63]:
my3 = pd.Series({'a': 1,'b':2,'c':3})
my3

a    1
b    2
c    3
dtype: int64

In [67]:
my3.name = 'numbers'
my3.index.name = 'sss'
my3

sss
a    1
b    2
c    3
Name: numbers, dtype: int64

In [69]:
my3.index = ['A','B','C']
my3

A    1
B    2
C    3
Name: numbers, dtype: int64

In [75]:
rr = pd.DataFrame({
    'family': ['Mom','Dad'],
    'age':    [35,45],
    'sex':    ['F','M']
})
rr

family  age sex
0    Mom   35   F
1    Dad   45   M

In [76]:
rr['family']

0    Mom
1    Dad
Name: family, dtype: object

In [78]:
rr.columns

Index(['family', 'age', 'sex'], dtype='object')

In [79]:
rr.index

RangeIndex(start=0, stop=2, step=1)

In [80]:
rr = pd.DataFrame({
    'family': ['Mom','Dad'],
    'age':    [35,45],
    'sex':    ['F','M']
}, index = ['M','D'])
rr

family  age sex
M    Mom   35   F
D    Dad   45   M

In [82]:
rr.index.name = 'tree'
rr

family  age sex
tree                
M       Mom   35   F
D       Dad   45   M

In [83]:
rr['age']

tree
M    35
D    45
Name: age, dtype: int64

In [86]:
rr.loc['M']

family    Mom
age        35
sex         F
Name: M, dtype: object

In [90]:
rr.iloc[1]

family    Dad
age        45
sex         M
Name: D, dtype: object

In [91]:
rr.loc[['M','D'], 'age']

tree
M    35
D    45
Name: age, dtype: int64

In [92]:
rr.loc[['M','D'], :]

family  age sex
tree                
M       Mom   35   F
D       Dad   45   M

In [94]:
rr.reset_index()

tree family  age sex
0    M    Mom   35   F
1    D    Dad   45   M

In [105]:
rr = rr.rename(columns={'age': 'AGE'})
rr

family  AGE
tree            
M       Mom   35
D       Dad   45

In [106]:
pass_data = pd.read_csv('titanic.csv')
pass_data

FileNotFoundError: [Errno 2] File b'titanic.csv' does not exist: b'titanic.csv'