# Markdown


# Заголовок первого уровня #
## Заголовок h2
### Заголовок h3
#### Заголовок h4
##### Заголовок h5
###### Заголовок h6

### Списки
- El1
- El2
- El3

* El1
* El2
    * El2.1
    *El2.2
* El3

1. El1
2. El2
    1. El1 inner
    2. El2 inner
3. El3

0. El1
0. El2
0. El3
0. El4


* El1
* El2
* El3

    El4

### Цитаты

> First
> Second
> Third
>
> Fourth

> ## Header.
>
> 1. First
> 2. Second
>
>> Inner
>
> Example code
>
> return shel_exec("echo %input)

    ### Исходный код
    
    <nav class="nav nav-primary">
    <ul>
        <li class="tab-convesation active">
        <a href="#" data-role="post-count" class="publisher-nav-color" data-nav=converstion"

### Горизонтальная черта

***

### Ссылки

Это - [ссылка с title](http://example.com/link "Ссылка")
Это - [без title](http://example.com/link)

[пример][1] [нескольких][2] [ссылок][id]
[короткая запись][]

[1]: http://example.com/ "Title"
[2]: http://example.com/some
[3]: http://example.com/links (Title)
[короткая запись]: http://example.com/short

### Emphasis

_italic_ и это *italic* 
__strong__
**strong**
***Жирный и наклонный***

### Зачеркивание

~~Зачеркнуто~~

## Картинки 

Без 'alt' текста

![](//placehold.it/160x100)

С альтом и таййтлом

![Alt text](//placehold.it/160x100 "Title")

Картинки - сноски

![Картинка][image1]
![Картинка][image2]
![Картинка][image3]

[image1]: //placehold.it/200x200
[image2]: //placehold.it/300x200
[image3]: //placehold.it/200x250

Картинки - ссылки:

[![Alt text](//placehold.it/200x200)](http://example.com/)

# Numpy

In [2]:
import numpy as np

In [3]:
vec = np.array([1, 2, 3])
vec.ndim # Количество осей

1

In [4]:
mat = np.array ([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

In [5]:
vec.shape

(3,)

In [6]:
mat.dtype.name

'int32'

In [7]:
mat.itemsize

4

## Создание массивов

In [8]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [9]:
A = np.array([1, 2, 3], dtype = float)
A

array([1., 2., 3.])

In [10]:
B = np.array([(1, 2, 3), (4, 5, 6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.zeros((3,))

array([0., 0., 0.])

In [12]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.empty((2, 5))

array([[8.98825982e-312, 1.97626258e-322, 0.00000000e+000,
        0.00000000e+000, 6.23037656e-307],
       [1.16095484e-028, 1.71872050e+161, 6.32672818e+180,
        4.74483502e+170, 1.35570811e+295]])

In [15]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [16]:
np.arange(2.5, 8.7, 0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [17]:
np.linspace(2, 18, 14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [18]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.arange(8).reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
C = np.arange(6).reshape(2, -1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [22]:
A = np.arange(6).reshape(2, -1)
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [23]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [24]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [25]:
a = np.arange(3)
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [26]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

## Базовые операции

In [27]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [28]:
print (A)
print (B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [30]:
A * 1.0 / 8

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [31]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [33]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [34]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [35]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [36]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [37]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [38]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
A.min()

0

In [40]:
A.max(axis = 0)

array([6, 7, 8])

In [41]:
A.sum(axis = 1)

array([ 3, 12, 21])

## Индексация

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[2:5]

array([2, 3, 4])

In [44]:
a[3:8:2]

array([3, 5, 7])

In [45]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [46]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [47]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [48]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [49]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [50]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [51]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

In [52]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [54]:
A[np.logical_and(A != 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [55]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [56]:
start = time.process_time()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.process_time() - start)

0.984375


In [57]:
start = time.process_time()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.process_time() - start)

0.859375


In [58]:
start = time.process_time()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.process_time() - start)

0.0625


In [59]:
start = time.process_time()
ans = A_quick_arr.dot(B_quick_arr)
print(time.process_time() - start)

0.0625


# Pandas

## Series

In [60]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [61]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [62]:
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [63]:
my_series[4]

9

In [64]:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [65]:
my_series2[['a', 'b', 'f']]

a     5
b     6
f    10
dtype: int64

In [66]:
my_series2[['a', 'b', 'f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [67]:
my_series2[my_series2 > 0] 

c    7
d    8
e    9
dtype: int64

In [68]:
my_series2[my_series2 > 0] * 2

c    14
d    16
e    18
dtype: int64

In [69]:
my_series3 = pd.Series({'a': 5, 'b': 6, 'c': 7, 'd': 8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [70]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [71]:
my_series3.index = ['A', 'B', 'C', 'D']
my_series3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

## DataFrame

In [72]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [73]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [74]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [75]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [76]:
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
}, index = ['KZ', 'RU', 'BY', 'UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [77]:
df.index = ['KZ', 'RU', 'BY', 'UA']
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [78]:
df['country']

Country Code
KZ    Kazakhstan
RU        Russia
BY       Belarus
UA       Ukraine
Name: country, dtype: object

In [79]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [80]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [82]:
df.loc[['KZ', 'RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [83]:
df.loc['KZ':'BY',:]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [85]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [86]:
df.reset_index()

Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [88]:
df['density'] = df['population'] / df['square'] * 1000000
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [89]:
df.drop(['density'], axis = 'columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [90]:
df = df.rename(columns={'Country Code': 'country code'})
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550