In [1]:
import numpy as np

In [3]:
vec = np.array([1,2,3])

In [4]:
vec.ndim

1

In [6]:
mat = np.array([[1,2,3],[4,5,6]])
mat.ndim
               

2

In [9]:
vec.shape

(3,)

In [10]:
mat.dtype.name

'int32'

In [11]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [12]:
A = np.array([1,2,3], dtype = float)
A

array([ 1.,  2.,  3.])

In [13]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.zeros((3,))

array([ 0.,  0.,  0.])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
np.empty((2,5))

array([[  7.83947015e-312,   2.27270197e-322,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  1.16095484e-028,   6.97283618e+228,   4.02992590e-144,
          9.80058441e+252,   1.23971686e+224]])

In [18]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [19]:
np.arange(2.28,13.37,.300)

array([  2.28,   2.58,   2.88,   3.18,   3.48,   3.78,   4.08,   4.38,
         4.68,   4.98,   5.28,   5.58,   5.88,   6.18,   6.48,   6.78,
         7.08,   7.38,   7.68,   7.98,   8.28,   8.58,   8.88,   9.18,
         9.48,   9.78,  10.08,  10.38,  10.68,  10.98,  11.28,  11.58,
        11.88,  12.18,  12.48,  12.78,  13.08])

In [20]:
np.linspace(2,18,14)

array([  2.        ,   3.23076923,   4.46153846,   5.69230769,
         6.92307692,   8.15384615,   9.38461538,  10.61538462,
        11.84615385,  13.07692308,  14.30769231,  15.53846154,
        16.76923077,  18.        ])

In [22]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.arange(8).reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
C = np.arange(8).reshape((2,-1))
C

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
C.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [29]:
A = np.arange(6).reshape((2,-1))
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [30]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [31]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [32]:
a = np.arange(3)
np.tile(a, (2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [34]:
np.tile(a, (4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [45]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-45-504a7a4a8544>, line 3)

In [51]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [53]:
A*1.0/B

array([[ 0.        ,  0.5       ,  0.66666667],
       [ 0.75      ,  0.8       ,  0.83333333],
       [ 0.85714286,  0.875     ,  0.88888889]])

In [54]:
A+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
3*A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [60]:
A**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [61]:
A*B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [62]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [65]:
np.tile(np.arange(0, 40, 10), (3,1)).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [67]:
np.exp(A)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

In [68]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
A.min()

0

In [71]:
A.max(axis = 0)

array([6, 7, 8])

In [72]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [73]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a[2:5]

array([2, 3, 4])

In [75]:
a[3:8:2]

array([3, 5, 7])

In [78]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [79]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [80]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [81]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [82]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [83]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [84]:
A[[2,4,5], [0,1,3]]

array([18, 37, 48])

In [86]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [89]:
A[np.logical_and(A != 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [90]:
import time
A_q = np.random.normal(size = (1000000,))
B_q = np.random.normal(size = (1000000,))
A_s, B_s = list(A_q), list(B_q)

In [97]:
start = time.clock()
ans = 0
for i in range(len(A_s)) :
    ans += A_s[i] * B_s[i]
print(time.clock() - start)

0.5408485475778235


In [98]:
start = time.clock()
ans = sum([A_s[i] * B_s[i] for i in range(1000000)])
print(time.clock() - start)

0.47816242882196036


In [99]:
start = time.clock()
ans = np.sum(A_q * B_q)
print(time.clock() - start)

0.022772927264924192


In [104]:
start = time.clock()
ans = A_q.dot(B_q)
print(time.clock() - start)

0.0030432117407599435
