In [1]:
import numpy as np

In [2]:
vec = np.array([5, 6 ,7])   #создание одномерного массива
vec.ndim    #показывает количество осей

1

In [3]:
mat = np.array([[5, 6, 7],[3, 2, 1]])    #создание двумерного массива
mat.ndim

2

In [4]:
vec.shape   #узнать длину массива

(3,)

In [5]:
mat.dtype.name    #узнать тип данных массива

'int32'

In [7]:
mat.itemsize    #узнать размер элемента в байтах

4

In [8]:
a = np.array([5, 6, 7])
a

array([5, 6, 7])

In [9]:
a = np.array([5, 6, 7], dtype = float)    #задается тип данных массива
a

array([5., 6., 7.])

In [11]:
b = np.array([[5, 6, 7],[8, 9, 0]])
b

array([[5, 6, 7],
       [8, 9, 0]])

In [12]:
np.zeros((3,))   #создание массива с базовыми значениями равными 0

array([0., 0., 0.])

In [13]:
np.ones((3,4))    #создание массива с базовыми значениями равными 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.identity(4)    #создание еденичной матрицы

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.empty((3,5))    #создание массива с пустыми базовыми значениями

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.arange(3,30,3)    #аналогично range, правая граница не включается

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
np.arange(3.5,11.4,1.3)    #может работать с вещественными

array([ 3.5,  4.8,  6.1,  7.4,  8.7, 10. , 11.3])

In [19]:
np.arange(9).reshape(3,3)    #реструктуризация массива

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.arange(8).reshape(2, -1)    #при -1 длина определяется автоматически

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
c = np.arange(6).reshape(2, -1)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
c.T    #транспонирование

array([[0, 3],
       [1, 4],
       [2, 5]])

In [24]:
A = np.arange(8).reshape(2, -1)
np.hstack((A, A**2))    #объединение массивов по горизонтали

array([[ 0,  1,  2,  3,  0,  1,  4,  9],
       [ 4,  5,  6,  7, 16, 25, 36, 49]])

In [25]:
A = np.arange(8).reshape(2, -1)
np.vstack((A, A**2))    #объединение массивов по вертикали

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [26]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  4,  9],
       [ 4,  5,  6,  7, 16, 25, 36, 49]])

In [28]:
a = np.arange(3)
np.tile(a,(2, 2))    #повтор массива

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [29]:
a = np.arange(3)
np.tile(a,(4, 1)) 

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [30]:
A = np.arange(9).reshape(3,3)
B = np.arange(1, 10).reshape(3,3)

In [32]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [35]:
A * 1.0 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [36]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [38]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [39]:
A * B #поэлементное!

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [40]:
A.dot(B)    #матричное

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [42]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1 , 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [43]:
np.exp(A)    #sin, exp, cos и т. д. применяются поэлементно!

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [44]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
A.min()

0

In [46]:
A.max(axis = 0)    #вдоль оси

array([6, 7, 8])

In [47]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [48]:
a = np.arange(10)

In [49]:
a[2:5]

array([2, 3, 4])

In [50]:
a[3:8:2]

array([3, 5, 7])

In [51]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [52]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [53]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [54]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [55]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [56]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

In [58]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [60]:
A[np.logical_and(A != 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [62]:
import time
A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))
A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [64]:
start = time.clock()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.clock() - start)

c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


0.7938959999992221


c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """


In [65]:
start = time.clock()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.clock() - start)

c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


0.7341536000003543


c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [66]:
start = time.clock()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.clock() - start)

0.11852830000134418


c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [67]:
start = time.clock()
ans = A_quick_arr.dot(B_quick_arr)
print(time.clock() - start)

0.16736390000005485


c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
c:\users\днс нн\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until
