# Розно К.В 0 Лабораторная работа

# Заголовок

## Заголовок поменьше

### Заголовок еще меньше

#### И так далее, и так далее

- элемент 1
- элемент 2
- элемент 3

* Элемент первого уровня
* Элемент первого уровня
    * Вложенный элемент
    * Еще один вложенный элемент
        * Вложенный во вложенный элемент
        * Ну и так далее

А вот тут цитата
> Возможно я пойму как программировать, но это не точно

Черта?
***

~~Я этого не говорил~~

*Вот это должен быть курсив*

**А вот это жирный текст**

***А вот это жирный курсив***

(http://etossilka.com/ "Ого, а вот это должно быть ссылка?")

In [2]:
import numpy as np

In [3]:
vec = np.array([1, 2, 3])
vec.ndim

1

In [4]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

In [5]:
vec.shape

(3,)

In [6]:
mat.shape

(2, 3)

In [7]:
mat.dtype

dtype('int32')

In [8]:
np.zeros((3,))

array([0., 0., 0.])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty((2, 3, 4))

array([[[2.05833592e-312, 6.79038654e-313, 6.79038653e-313,
         2.37663529e-312],
        [2.05833592e-312, 2.41907520e-312, 2.56761491e-312,
         1.93101617e-312],
        [1.03977794e-312, 6.79038653e-313, 9.33678148e-313,
         1.08221785e-312]],

       [[9.33678148e-313, 1.93101617e-312, 9.33678148e-313,
         1.12465777e-312],
        [6.79038653e-313, 1.97345609e-312, 8.70018275e-313,
         2.31297541e-312],
        [2.46151512e-312, 2.33419537e-312, 2.22809558e-312,
         2.22507386e-306]]])

In [13]:
np.arange(9).reshape(3, -1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a = np.arange(3)

In [15]:
print(a)

[0 1 2]


In [16]:
a = np.tile(a, (3, 1))
print(a)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [17]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [18]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [21]:
A / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [22]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [23]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
A ** 5

array([[    0,     1,    32],
       [  243,  1024,  3125],
       [ 7776, 16807, 32768]], dtype=int32)

In [26]:
A * A

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [27]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [28]:
A.min()

0

In [29]:
A.max(0)

array([6, 7, 8])

In [32]:
A.reshape(3, 1, 3)

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [33]:
A.sum(0)

array([ 9, 12, 15])

In [34]:
A[np.logical_and(A != 7, A % 5 != 3)]

array([0, 1, 2, 4, 5, 6])

In [35]:
import pandas as pd
ms = pd.Series([5, 6, 7, 8, 9, 10])
ms

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [36]:
ms = pd.Series([1, 2, 3, 4, 5], index = ['q', 'w', 'e', 'r', 't'])
ms

q    1
w    2
e    3
r    4
t    5
dtype: int64

In [38]:
ms.name = 'Номера'
ms.index.name = 'Буквы'
ms

Буквы
q    1
w    2
e    3
r    4
t    5
Name: Номера, dtype: int64

In [39]:
ms[['q', 'e', 'r']] = 0
ms

Буквы
q    0
w    2
e    0
r    0
t    5
Name: Номера, dtype: int64

In [40]:
df = pd.DataFrame({
    'country': ['Kazakhtan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
df

country  population    square
0  Kazakhtan       17.04   2724902
1     Russia      143.50  17125191
2    Belarus        9.50    207600
3    Ukraine       45.50    603628

In [41]:
df['country']

0    Kazakhtan
1       Russia
2      Belarus
3      Ukraine
Name: country, dtype: object

In [42]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [43]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [44]:
df = pd.DataFrame({
    'country': ['Kazakhtan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
}, index = ['KZ', 'RU', 'BY', 'UA'])
df

country  population    square
KZ  Kazakhtan       17.04   2724902
RU     Russia      143.50  17125191
BY    Belarus        9.50    207600
UA    Ukraine       45.50    603628

In [45]:
df.index.name = 'Country Code'
df

country  population    square
Country Code                                 
KZ            Kazakhtan       17.04   2724902
RU               Russia      143.50  17125191
BY              Belarus        9.50    207600
UA              Ukraine       45.50    603628

In [46]:
df.loc['KZ']

country       Kazakhtan
population        17.04
square          2724902
Name: KZ, dtype: object

In [47]:
df.loc['KZ':'BY', 'population']

Country Code
KZ     17.04
RU    143.50
BY      9.50
Name: population, dtype: float64

In [48]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                     
KZ            Kazakhtan   2724902
RU               Russia  17125191
UA              Ukraine    603628

In [49]:
df['density'] = df['population'] / df['square'] * 1000000
df

country  population    square    density
Country Code                                            
KZ            Kazakhtan       17.04   2724902   6.253436
RU               Russia      143.50  17125191   8.379469
BY              Belarus        9.50    207600  45.761079
UA              Ukraine       45.50    603628  75.377550

In [50]:
df.drop(['density'], axis = 'columns')

country  population    square
Country Code                                 
KZ            Kazakhtan       17.04   2724902
RU               Russia      143.50  17125191
BY              Belarus        9.50    207600
UA              Ukraine       45.50    603628

In [51]:
df.rename(columns = {'Country Code': 'country_code'})

country  population    square    density
Country Code                                            
KZ            Kazakhtan       17.04   2724902   6.253436
RU               Russia      143.50  17125191   8.379469
BY              Belarus        9.50    207600  45.761079
UA              Ukraine       45.50    603628  75.377550

In [98]:
import pandas as pd
titanic = pd.read_csv('titanic.csv')
print(titanic)

FileNotFoundError: [Errno 2] File titanic.csv does not exist: 'titanic.csv'

In [88]:
print(titanic.groupby(['Sex', 'Survived'])['PassengerId'].count())

KeyError: 'Sex'

In [72]:
print(titanic.groupby(['Pclass', 'Survived'])['PassengerId'].count())

NameError: name 'titanic' is not defined

In [73]:
%matplotlib inline

In [74]:
titanic.head(6)

NameError: name 'titanic' is not defined

In [75]:
titanic.columns

NameError: name 'titanic' is not defined

In [76]:
titanic.iloc[1:2, 1:3]

NameError: name 'titanic' is not defined

In [77]:
titanic['Name'].head()

NameError: name 'titanic' is not defined

In [78]:
titanic[titanic['Sex'] == 'male']

NameError: name 'titanic' is not defined

In [79]:
titanic[(titanic['Sex'] == 'female') & 
    (titanic.Age > 18) & 
    (titanic['Age'] < 25) & 
    (titanic['SibSp'] == 0) & 
    (titanic['Parch'] == 0)].shape

NameError: name 'titanic' is not defined

In [80]:
def get_last_name(name):
    return name.split(',')[0].strip()

last_names = titanic['Name'].apply(get_last_name)
last_names.head()

NameError: name 'titanic' is not defined

In [81]:
titanic['Last_name'] = last_names
titanic.head()

NameError: name 'last_names' is not defined

In [82]:
titanic.drop('Last_name', axis = 1, inplace = True)
titanic.head()

NameError: name 'titanic' is not defined

In [83]:
titanic['Parch'].isnull().head()

NameError: name 'titanic' is not defined

In [85]:
titanic.sort_values(by = ['Survived', 'SibSp'], ascending = [True, False]).head()

NameError: name 'titanic' is not defined

In [86]:
titanic.groupby('Survived')['SibSp'].describe()

NameError: name 'titanic' is not defined

In [96]:
titanic.groupby('Sex')['Age'].mean()

KeyError: 'Sex'

In [97]:
titanic.groupby(['Sex', 'Pclass'])['Survived'].mean()

KeyError: 'Sex'