# Заголовок h2
# Заголовок h3

# заголовок h5

- элемент 1
- элемент 2
- элемент 3
* элемент 1
* элемент 2
    * элемент 2.1

1. элемент 1
2. элемент 2
    1. элемент 1
    2. элемент 2
3. элемент 3

###### заголовок h6

In [2]:
0. элемент 1
0. элемент 0

SyntaxError: invalid syntax (<ipython-input-2-87189be7b4fc>, line 1)

0. элемент 1
0. элемент 0

> my name is Ann

--- jhkjygku

---

In [3]:
[ссылка на title элементом](http://example.com/link "я ссылка")

SyntaxError: invalid syntax (<ipython-input-3-f0844d8f587a>, line 1)

[ссылка на title элементом](http://example.com/link "я ссылка")

**pfrfp

In [4]:
* hkufju

SyntaxError: can't use starred expression here (<ipython-input-4-00c29bfb5f4b>, line 4)

* yjgfjutgd

*dhfvdf*

![Alt text](//placehold.it/150x100 "Можно сдать title")

![картинка][image1]

In [5]:
![картинка][image1]

"[Є авЁ­Є ][image1]" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


![картинка][image1]

In [6]:
import numpy as np

In [7]:
mat = np.array ([[1,2,3][4,5,6]])

TypeError: list indices must be integers or slices, not tuple

In [8]:
mat = np.array([[1,2,3][4,5,6]])
mat.ndim

TypeError: list indices must be integers or slices, not tuple

In [9]:
mat = np.array([[1,2,3],[4,5,6]])
mat.ndim

2

In [10]:
mat.dtype.name

'int32'

In [11]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [12]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [13]:
B = np.onec((3,))
B

AttributeError: module 'numpy' has no attribute 'onec'

In [14]:
B = np.onec((3,4))
B

AttributeError: module 'numpy' has no attribute 'onec'

In [15]:
np.onec((3,4))

AttributeError: module 'numpy' has no attribute 'onec'

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty((2,5))

array([[3.54228043e-316, 2.27270197e-322, 0.00000000e+000,
        0.00000000e+000, 2.14321575e-312],
       [1.16095484e-028, 6.18618429e+223, 4.03617331e-144,
        9.80058441e+252, 1.23971686e+224]])

In [19]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [20]:
np.linspace(2,18,14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
C = np.arange(6).reshape(2,-1) 

In [23]:
C


array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [25]:
np.vstack((C, C**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [26]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

In [27]:
A+B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [28]:
A+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
A**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [30]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [31]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [32]:
A.min

<function ndarray.min>

In [33]:
A.min()

0

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[2,5]

IndexError: too many indices for array

In [36]:
a[2:5]

array([2, 3, 4])

In [37]:
A = np.arange(81).reshape(9,-1)

In [38]:
A


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [39]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [40]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [41]:
A = np.arange(11)

In [42]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [43]:
A[np.logical_and(A  != 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])