In [1]:
2+4

6

![](//placehold.it/150x100)

# header 1

- 1.markdown
    - список
    - заголовок
    - абзацы
    - цитаты
- 2.
> цитата.
>
> цитата 2.
- абзац 1

- абзац 2

[ссылка](http://example.com "example")

In [2]:
import numpy as np

In [3]:
vec = np.array([1, 2, 3, 4, 5])
vec.ndim

1

In [5]:
mat = np.array([[1, 2], [2, 4]])
mat.ndim

2

In [6]:
vec.shape

(5,)

In [9]:
mat.dtype.name 

'int32'

In [8]:
mat.itemsize

4

In [12]:
A = np.array([1, 2, 3, 4])
A

array([1, 2, 3, 4])

In [13]:
A = np.array([1, 2, 3], dtype = float)
A

array([ 1.,  2.,  3.])

In [15]:
B = np.array([(1, 3, 5),(2, 4, 6)])
B

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
np.zeros((6,))

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [19]:
np.empty((2, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [21]:
np.arange(0.3, 8.7, 0.6)

array([ 0.3,  0.9,  1.5,  2.1,  2.7,  3.3,  3.9,  4.5,  5.1,  5.7,  6.3,
        6.9,  7.5,  8.1])

In [22]:
np.linspace(2, 18, 14)

array([  2.        ,   3.23076923,   4.46153846,   5.69230769,
         6.92307692,   8.15384615,   9.38461538,  10.61538462,
        11.84615385,  13.07692308,  14.30769231,  15.53846154,
        16.76923077,  18.        ])

In [23]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.arange(18).reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [26]:
c = np.arange(6).reshape(2, - 1)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
c.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [29]:
A = np.arange(8).reshape(2, -1)
np.hstack((A, A**3))

array([[  0,   1,   2,   3,   0,   1,   8,  27],
       [  4,   5,   6,   7,  64, 125, 216, 343]])

In [30]:
np.vstack((A, A**2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [31]:
np.concatenate((A))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  4,  9],
       [ 4,  5,  6,  7, 16, 25, 36, 49]])

In [41]:
np.tile(A, (4, 3))

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]])

In [45]:
print (A)
print (B)

[[0 1 2 3]
 [4 5 6 7]]
[[1 3 5]
 [2 4 6]]


In [48]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1,10).reshape(3, 3)
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [49]:
A * 1.0 / B

array([[ 0.        ,  0.5       ,  0.66666667],
       [ 0.75      ,  0.8       ,  0.83333333],
       [ 0.85714286,  0.875     ,  0.88888889]])

In [50]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
3*A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [53]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [54]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [55]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [56]:
np.exp(A)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

In [57]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
A.min()

0

In [59]:
A.max(axis = 0)

array([6, 7, 8])

In [60]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [62]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a[2:5]

array([2, 3, 4])

In [65]:
a[3:8:2]

array([3, 5, 7])

In [66]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [67]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [68]:
A[:, 2:4] #все столбцы, но 2-3 элемент из строки

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [69]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [70]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [71]:
A[-3]

array([54, 55, 56, 57, 58, 59, 60, 61, 62])

In [72]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [73]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

In [75]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [77]:
A[np.logical_and(A != 7, A % 5 !=3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [78]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))
A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [81]:
start = time.clock()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.clock() - start)

0.49294773727658026


In [82]:
start = time.clock()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.clock() - start)

0.4825759302794381


In [83]:
start = time.clock()
ans = np.sum(A_quick_arr + B_quick_arr)
print(time.clock() - start)

0.013482198366546072


In [84]:
start = time.clock()
ans = A_quick_arr.dot(B_quick_arr)
print(time.clock() - start)

0.7282383789514597


# Pandas

In [86]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [87]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [89]:
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [90]:
my_series[4]

9

In [93]:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index = ['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [94]:
my_series2[['a', 'b', 'f']]

a     5
b     6
f    10
dtype: int64

In [96]:
my_series2[['a', 'b', 'f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [98]:
my_series2[my_series2 > 0]

c    7
d    8
e    9
dtype: int64

In [99]:
my_series2[my_series2 > 0]*2

c    14
d    16
e    18
dtype: int64

In [100]:
my_series3 = pd.Series({'a': 5, 'b': 6, 'c': 7, 'd': 8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [101]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [102]:
df = pd.DataFrame({'country':['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
                  'population' :[17.04, 143.5, 9.5, 45.5],
                  'square':[2724902, 17125191, 207600, 603628]})
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [103]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [104]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [105]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [47]:
df = pd.DataFrame({'country':['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
                  'population' :[17.04, 143.5, 9.5, 45.5],
                  'square':[2724902, 17125191, 207600, 603628]
                  }, index = ['KZ', 'RU', 'BY', 'UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [107]:
df.index = ['KZ', 'RU', 'BY', 'UA']
df.index.name = 'Country code'
df

country  population    square
Country code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [108]:
df['country']

Country code
KZ    Kazakhstan
RU        Russia
BY       Belarus
UA       Ukraine
Name: country, dtype: object

In [109]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [110]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [111]:
df.loc[['KZ', 'RU'],'population']

Country code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [112]:
df.loc['KZ': 'RU', :]

country  population    square
Country code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191

In [114]:
df[df.population > 10][['country', 'square']]

country    square
Country code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [115]:
df.reset_index()

Country code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [116]:
df['density'] = df['population']/df['square']
df

country  population    square   density
Country code                                            
KZ            Kazakhstan       17.04   2724902  0.000006
RU                Russia      143.50  17125191  0.000008
BY               Belarus        9.50    207600  0.000046
UA               Ukraine       45.50    603628  0.000075

In [117]:
df.drop(['density'], axis='columns')

country  population    square
Country code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [119]:
df = df.rename(columns={'Country code': 'country code'})
df

country  population    square   density
Country code                                            
KZ            Kazakhstan       17.04   2724902  0.000006
RU                Russia      143.50  17125191  0.000008
BY               Belarus        9.50    207600  0.000046
UA               Ukraine       45.50    603628  0.000075

In [122]:
titanic_df = pd.read_csv('titanic.csv')
print(titanic_df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [124]:
print(titanic_df.groupby(['Sex', 'Survived'])['PassengerId'].count())

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: PassengerId, dtype: int64


In [125]:
print(titanic_df.groupby(['Pclass', 'Survived'])['PassengerId'].count())

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: PassengerId, dtype: int64


In [4]:
import pandas as pd
#%matplotlibinline
pass_data = pd.read_csv('titanic.csv')
pass_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

- 46 end

In [6]:
pass_data.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [7]:
pass_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
pass_data[2:5]

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
2                        Heikkinen, Miss. Laina  female  26.0      0      0   
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   

             Ticket    Fare Cabin Embarked  
2  STON/O2. 3101282   7.925   NaN        S  
3            113803  53.100  C123        S  
4            373450   8.050   NaN        S

In [9]:
pass_data.iloc[1:5, 1:3]

Survived  Pclass
1         1       1
2         1       3
3         1       1
4         0       3

In [12]:
pass_data['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [13]:
pass_data[['Name', 'Sex', 'Parch']].head()

Name     Sex  Parch
0                            Braund, Mr. Owen Harris    male      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      0
2                             Heikkinen, Miss. Laina  female      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      0
4                           Allen, Mr. William Henry    male      0

In [15]:
pass_data[pass_data['Sex'] == 'female'].head() #женщины на борту

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [16]:
# женщины старше 60 и мужчины на борту
pass_data[(pass_data['Sex'] == 'female') & (pass_data['Age']  >= 60) | (pass_data['Sex'] == 'male')].head()

PassengerId  Survived  Pclass                            Name   Sex   Age  \
0            1         0       3         Braund, Mr. Owen Harris  male  22.0   
4            5         0       3        Allen, Mr. William Henry  male  35.0   
5            6         0       3                Moran, Mr. James  male   NaN   
6            7         0       1         McCarthy, Mr. Timothy J  male  54.0   
7            8         0       3  Palsson, Master. Gosta Leonard  male   2.0   

   SibSp  Parch     Ticket     Fare Cabin Embarked  
0      1      0  A/5 21171   7.2500   NaN        S  
4      0      0     373450   8.0500   NaN        S  
5      0      0     330877   8.4583   NaN        Q  
6      0      0      17463  51.8625   E46        S  
7      3      1     349909  21.0750   NaN        S

In [19]:
pass_data[(pass_data.Sex == 'female') & (pass_data.Age > 18) & (pass_data.Age < 25) &
(pass_data.SibSp == 0) & (pass_data.Parch == 0)].shape

(25, 12)

In [22]:
pass_data.Age.hist(bins = 30)

In [23]:
pass_data.rename(columns={'Sex': 'sex'}, inplace=True)
pass_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [25]:
def get_last_name(name):
    return name.split(',')[0].strip()
last_names = pass_data['Name'].apply(get_last_name)
last_names.head()

0       Braund
1      Cumings
2    Heikkinen
3     Futrelle
4        Allen
Name: Name, dtype: object

In [26]:
pass_data['Last_name'] = last_names
pass_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Last_name  
0      0         A/5 21171   7.2500   NaN        S     Braund  
1      0          PC 17599  71.2833   C85        C    Cumings  
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      0            113803  53.1000  C123        S   Futrelle  
4      0            373450   8.0500   NaN        S      Allen

In [27]:
pass_data.drop('Last_name', axis = 1, inplace=True)
pass_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [29]:
pass_data['Cabin'].isnull().head()

0     True
1    False
2     True
3    False
4     True
Name: Cabin, dtype: bool

In [30]:
pass_data[pass_data['Cabin'].notnull()].head() # пассажиры с известным номером шлюпки эвакуации

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [31]:
pass_data.sort_values(by=['Pclass', 'Fare'], ascending=True).head()

PassengerId  Survived  Pclass                             Name   sex  \
263          264         0       1            Harrison, Mr. William  male   
633          634         0       1    Parr, Mr. William Henry Marsh  male   
806          807         0       1           Andrews, Mr. Thomas Jr  male   
815          816         0       1                 Fry, Mr. Richard  male   
822          823         0       1  Reuchlin, Jonkheer. John George  male   

      Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
263  40.0      0      0  112059   0.0   B94        S  
633   NaN      0      0  112052   0.0   NaN        S  
806  39.0      0      0  112050   0.0   A36        S  
815   NaN      0      0  112058   0.0  B102        S  
822  38.0      0      0   19972   0.0   NaN        S

In [32]:
pass_data.sort_values(by=['Pclass', 'Fare'], ascending=[True, False]).head()

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   
27            28         0       1      Fortune, Mr. Charles Alexander   
88            89         1       1          Fortune, Miss. Mabel Helen   

        sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C  
27     male  19.0      3      2     19950  263.0000  C23 C25 C27        S  
88   female  23.0      3      2     19950  263.0000  C23 C25 C27        S

In [33]:
pass_data.groupby('sex') # разбиение всех объектов на 2 группы по полу

In [34]:
pass_data.groupby('sex')['Pclass'].value_counts()

sex     Pclass
female  3         144
        1          94
        2          76
male    3         347
        1         122
        2         108
Name: Pclass, dtype: int64

In [36]:
pass_data.groupby('Pclass')['Fare'].describe()

count       mean        std  min       25%      50%   75%       max
Pclass                                                                     
1       216.0  84.154687  78.380373  0.0  30.92395  60.2875  93.5  512.3292
2       184.0  20.662183  13.417399  0.0  13.00000  14.2500  26.0   73.5000
3       491.0  13.675550  11.778142  0.0   7.75000   8.0500  15.5   69.5500

In [37]:
pass_data.groupby('sex')['Age'].mean()

sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [38]:
pass_data.groupby('sex')['Survived'].mean()

sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [39]:
pass_data.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [40]:
pass_data.groupby('sex', as_index=False)['Survived'].mean()

sex  Survived
0  female  0.742038
1    male  0.188908