In [2]:
import numpy as np

In [10]:
vec = np.array([1,2,3])
vec.ndim

1

In [11]:
vec.shape

(3,)

In [15]:
vec.itemsize

4

In [17]:
np.empty((2,5))

array([[              nan,   0.00000000e+000,   1.40659213e-311,
          2.02369289e-320,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000]])

In [18]:
np.arange(2.5,8,1)

array([ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5])

In [19]:
np.arange(2,8.7,1.5)

array([ 2. ,  3.5,  5. ,  6.5,  8. ])

In [25]:
np.linspace(2,18,14)

array([  2.        ,   3.23076923,   4.46153846,   5.69230769,
         6.92307692,   8.15384615,   9.38461538,  10.61538462,
        11.84615385,  13.07692308,  14.30769231,  15.53846154,
        16.76923077,  18.        ])

In [30]:
c = np.array([(2,4,5),(6,7,8)])
c

array([[2, 4, 5],
       [6, 7, 8]])

In [31]:
c.T

array([[2, 6],
       [4, 7],
       [5, 8]])

In [34]:
a = np.arange(3)
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [35]:
np.tile(a,(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [39]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

In [40]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [42]:
A * 1/B

array([[ 0.        ,  0.5       ,  0.66666667],
       [ 0.75      ,  0.8       ,  0.83333333],
       [ 0.85714286,  0.875     ,  0.88888889]])

In [43]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [45]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [46]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [47]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [48]:
np.exp(A)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

In [50]:
A.min()

0

In [55]:
A.max(axis = 0)

array([6, 7, 8])

In [56]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [59]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[2:5]

array([2, 3, 4])

In [63]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [64]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [65]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [66]:
A[A % 5 !=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10, 11, 12, 14, 15, 16, 17, 19, 20,
       21, 22, 24, 25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 37, 39, 40, 41,
       42, 44, 45, 46, 47, 49, 50, 51, 52, 54, 55, 56, 57, 59, 60, 61, 62,
       64, 65, 66, 67, 69, 70, 71, 72, 74, 75, 76, 77, 79, 80])