Some ya header

# Numpy

In [10]:
import numpy as np

In [11]:
vec = np.array([1, 2, 3])
vec.ndim #4

1

In [14]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

In [15]:
vec.shape

(3,)

# Создание массивов


In [17]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [21]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [22]:
B = np.array([(1, 2, 3), (4, 5, 6)])
B


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones((42,
        ))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.arange(2, 1434353, 44535)

array([      2,   44537,   89072,  133607,  178142,  222677,  267212,
        311747,  356282,  400817,  445352,  489887,  534422,  578957,
        623492,  668027,  712562,  757097,  801632,  846167,  890702,
        935237,  979772, 1024307, 1068842, 1113377, 1157912, 1202447,
       1246982, 1291517, 1336052, 1380587, 1425122])

In [54]:
np.linspace(5, 2000, 2555)

array([   5.        ,    5.78112764,    6.56225529, ..., 1998.43774471,
       1999.21887236, 2000.        ])

In [55]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
 np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
A = np.arange(6).reshape(2,-1)
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [59]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [65]:
a = np.arange(3)
np.tile(a, (4, 4))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [67]:
np.tile(A, (5, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [80]:
A = np.arange(9).reshape(3,3)
B = np.arange(1, 10).reshape(3,3)

In [81]:
A+B



array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [82]:
A*B


array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [83]:
A%B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [91]:
B



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
A+102


array([[102, 103, 104],
       [105, 106, 107],
       [108, 109, 110]])

In [95]:
A**B

array([[        0,         1,         8],
       [       81,      1024,     15625],
       [   279936,   5764801, 134217728]], dtype=int32)

In [96]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [102]:
np.cos(A*B)

array([[ 1.        , -0.41614684,  0.96017029],
       [ 0.84385396,  0.40808206,  0.15425145],
       [-0.39998531,  0.85322011, -0.96725059]])

In [103]:
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
A.min(0)

array([0, 1, 2])

In [109]:
A.max(0)

array([6, 7, 8])

In [111]:
A.sum(1)

array([ 3, 12, 21])

# Индексация

In [112]:
A[2:5]

array([[6, 7, 8]])

In [115]:
A[3:8:2]

array([], shape=(0, 3), dtype=int32)

In [116]:
A = np.arange(64).reshape(8, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [117]:
A[2:4]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [118]:
A[0:, 2:4]

array([[ 2,  3],
       [10, 11],
       [18, 19],
       [26, 27],
       [34, 35],
       [42, 43],
       [50, 51],
       [58, 59]])

In [120]:
A[2:5, 2:5]

array([[18, 19, 20],
       [26, 27, 28],
       [34, 35, 36]])

In [121]:
A[-2]

array([48, 49, 50, 51, 52, 53, 54, 55])

In [122]:
A[A % 5 !=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10, 11, 12, 14, 15, 16, 17, 19, 20,
       21, 22, 24, 25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 37, 39, 40, 41,
       42, 44, 45, 46, 47, 49, 50, 51, 52, 54, 55, 56, 57, 59, 60, 61, 62])

#  Зачем использовать наймпай :)

In [123]:
A = (NE SPORY: NAMNOGO: BISTREE)

SyntaxError: invalid syntax (<ipython-input-123-ab14a2d5e092>, line 1)

Pandas

# DataFrame и Series

## Series

In [124]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [126]:
my_series.index



RangeIndex(start=0, stop=6, step=1)

In [127]:

my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [128]:
my_series[4]

9

In [133]:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['b']

6

In [130]:
my_series2[['a', 'b', 'f']]

a     5
b     6
f    10
dtype: int64

In [132]:
my_series2[['a', 'b', 'f']]
my_series2

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64

In [134]:
my_series2[my_series2 > 0]


a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64

In [135]:
my_series2[my_series2 > 0] * 2

a    10
b    12
c    14
d    16
e    18
f    20
dtype: int64

In [142]:
my_series3 = pd.Series({'a': 7, 'b': 7, 'c': 7,}) #three topora:)
my_series3

a    7
b    7
c    7
dtype: int64

In [143]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    7
b    7
c    7
Name: numbers, dtype: int64

In [147]:
my_series3.index = ['A', 'B', 'C',]
my_series3


A    7
B    7
C    7
Name: numbers, dtype: int64

## DataFrame


In [148]:
 df = pd.DataFrame({
...     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
...     'population': [17.04, 143.5, 9.5, 45.5],
...     'square': [2724902, 17125191, 207600, 603628]
... })

df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [149]:
df['country']


0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [150]:
df.columns


Index(['country', 'population', 'square'], dtype='object')

In [151]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [158]:
df = pd.DataFrame({
...     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
...     'population': [17.04, 143.5, 9.5, 45.5],
...     'square': [2724902, 17125191, 207600, 603628]
... }, index=['KZ', 'RU', 'BY', 'USA:)'])
df

country  population    square
KZ     Kazakhstan       17.04   2724902
RU         Russia      143.50  17125191
BY        Belarus        9.50    207600
USA:)     Ukraine       45.50    603628

In [159]:
df.index

Index(['KZ', 'RU', 'BY', 'USA:)'], dtype='object')

In [160]:
df

country  population    square
KZ     Kazakhstan       17.04   2724902
RU         Russia      143.50  17125191
BY        Belarus        9.50    207600
USA:)     Ukraine       45.50    603628

In [162]:
df.index
df.index.name = "Country Code"
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
USA:)            Ukraine       45.50    603628

In [166]:
df["country"]

Country Code
KZ       Kazakhstan
RU           Russia
BY          Belarus
USA:)       Ukraine
Name: country, dtype: object

In [167]:
df.loc

In [169]:
df.loc["RU"]

country         Russia
population       143.5
square        17125191
Name: RU, dtype: object

In [173]:
df.iloc[1]

country         Russia
population       143.5
square        17125191
Name: RU, dtype: object

In [174]:
df[df.population > 10][["conury", "square"]]

KeyError: "['conury'] not in index"

In [175]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
USA:)            Ukraine    603628

In [176]:
df.reset_index()


Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3        USA:)     Ukraine       45.50    603628

In [177]:
df['density'] = df['population'] / df['square'] * 1000000
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
USA:)            Ukraine       45.50    603628  75.377550

In [178]:
df.drop(['density'], axis='columns')


country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
USA:)            Ukraine       45.50    603628

In [179]:
df = df.rename(columns={'Country Code': 'country_code'})
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
USA:)            Ukraine       45.50    603628  75.377550

# Группировка и агрегирование в pandas

Дальше делаю?