# Лабораторная работа 0
### Береснева Мария 18-ИВТ-2

# Markdown

### Краткое руководство

###### октуоктуол


адмщлавм

+ 1
+ 2
    + 2.1
    + 2.2
        + 2.2.1

---

[title](http://example.com/link "link")
[nontitle](http://example.com/link)

[пример][1] [нескольких][2] [ссылок][id]  [короткая запись][]

[1]: http://example.com/ "Optional Title Here"
[2]: http://example.com/some
[id]: http://example.com/links (Optional Title Here)
[короткая запись]: http://example.com/short

~~fghhj~~

In [5]:
import numpy as np

In [8]:
vec = np.array([1, 2, 3])
vec.ndim

1

In [9]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

In [10]:
vec.shape

(3,)

In [11]:
mat.shape

(2, 3)

In [12]:
mat.dtype

dtype('int32')

In [13]:
mat.itemsize

4

In [14]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.zeros((3,))

array([ 0.,  0.,  0.])

In [16]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [17]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
np.empty((2, 3, 4))

array([[[  1.69118108e-306,   9.34598926e-307,   9.45734481e-308,
           4.62170619e-289],
        [  6.23037657e-307,   3.56049165e-307,   1.37961641e-306,
           1.11258276e-307],
        [  8.06638505e-308,   8.34425615e-308,   3.78278853e-307,
           1.69118108e-306]],

       [[  1.11261570e-306,   6.23059726e-307,   2.22522597e-306,
           1.33511969e-306],
        [  1.37962320e-306,   9.34604358e-307,   9.79101082e-307,
           1.78020576e-306],
        [  1.69119873e-306,   2.22522868e-306,   1.24611809e-306,
           8.06632139e-308]]])

In [22]:
np.arange(9).reshape(3, -1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
a = np.arange(3)
print(a)
a = np.tile(a, (3, 1))
print(a)
a = np.tile(a, (2, 2))
print(a)

[0 1 2]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [25]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [27]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [29]:
A / B

array([[ 0.        ,  0.5       ,  0.66666667],
       [ 0.75      ,  0.8       ,  0.83333333],
       [ 0.85714286,  0.875     ,  0.88888889]])

In [30]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [31]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
A ** 10

array([[         0,          1,       1024],
       [     59049,    1048576,    9765625],
       [  60466176,  282475249, 1073741824]], dtype=int32)

In [33]:
A ** 9

array([[        0,         1,       512],
       [    19683,    262144,   1953125],
       [ 10077696,  40353607, 134217728]], dtype=int32)

In [34]:
A ** 3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

In [35]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [36]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [38]:
A * A

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [39]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [40]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
A.min()

0

In [44]:
A.max(0)

array([6, 7, 8])

In [45]:
A.max(1)

array([2, 5, 8])

In [46]:
A.max(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [47]:
A.reshape(1, 3, 3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [48]:
A.min(0)

array([0, 1, 2])

In [49]:
A.min(1)

array([0, 3, 6])

In [50]:
A.min(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [51]:
A.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
A.sum(0)

array([ 9, 12, 15])

In [53]:
A.sum(1)

array([ 3, 12, 21])

In [54]:
A.sum()

36

In [64]:
A[np.logical_and(A != 7, A % 5 != 3)]

array([0, 1, 2, 4, 5, 6])

In [68]:
import pandas as pd
ms = pd.Series([5, 6, 7, 8, 9, 10])
ms

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [70]:
ms = pd.Series([1, 2, 3, 4, 5], index = ['q', 'w', 'e', 'r', 't'])
ms

q    1
w    2
e    3
r    4
t    5
dtype: int64

In [72]:
ms.name = 'numbers'
ms.index.name = 'letters'
ms

letters
q    1
w    2
e    3
r    4
t    5
Name: numbers, dtype: int64