# Голубинов Владислав

# 18-ИВТ-3 
## h2
### h3
#### h4
##### h5
###### h6

* root
    * child

1. a1
2. a2

> quot

~~asd~~

*italic*

![](//placehold.it/150x150)

In [1]:
import numpy as np

In [2]:
vec = np.array([1,2,3])
vec.ndim

1

In [3]:
import numpy as np
mat = np.array([[1,2,3],[3,2,1]])
mat.ndim

2

In [4]:
vec.shape

(3,)

In [5]:
mat.dtype.name

'int64'

In [6]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [7]:
np.zeros((3,))

array([0., 0., 0.])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [11]:
np.arange(2.5,8.7,0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [12]:
np.linspace(2,18,14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [13]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
C = np.arange(6).reshape(2,-1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [17]:
A = np.arange(6).reshape(2,-1)
np.hstack((A,A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [18]:
a = np.arange(3)
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [19]:
np.tile(a,(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [20]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

In [21]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
A+B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [23]:
A*1.0/B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [24]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [25]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [26]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [27]:
np.tile(np.arange(0,40,10),(3,1)).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [28]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [29]:
A.min()

0

In [30]:
A.sum(axis=1)

array([ 3, 12, 21])

In [31]:
a = np.arange(10)

In [32]:
a[2:5]

array([2, 3, 4])

In [33]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [34]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [35]:
A[:,2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [36]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [37]:
A[A%5!=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10, 11, 12, 14, 15, 16, 17, 19, 20,
       21, 22, 24, 25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 37, 39, 40, 41,
       42, 44, 45, 46, 47, 49, 50, 51, 52, 54, 55, 56, 57, 59, 60, 61, 62,
       64, 65, 66, 67, 69, 70, 71, 72, 74, 75, 76, 77, 79, 80])

In [38]:
A[np.logical_and(A !=7,A%5!=3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21,
       22, 24, 25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 37, 39, 40, 41, 42,
       44, 45, 46, 47, 49, 50, 51, 52, 54, 55, 56, 57, 59, 60, 61, 62, 64,
       65, 66, 67, 69, 70, 71, 72, 74, 75, 76, 77, 79, 80])

In [39]:
import time 
arr = np.random.normal(size = (100000,))
arr1 = np.random.normal(size = (100000,))
a_list,b_list = list(arr),list(arr1)

In [40]:
start = time.clock()
ans = arr.dot(arr1)

In [41]:
print(time.clock() - start)

0.36922200000000016


In [42]:
import pandas as pd
%matplotlib inline

ModuleNotFoundError: No module named 'pandas'

In [ ]:
ms = pd.Series([5,6,7,8,9,10])
ms

In [ ]:
ms.index

In [ ]:
ms.values

In [ ]:
ms[4]

In [ ]:
ms2 = pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])

In [ ]:
ms2['f']

In [ ]:
ms3 = pd.Series({'a':5,'b':6,'c':7,'d':8})
ms3

In [ ]:
ms3.name = 'numbers'

In [ ]:
ms3.index.name = 'letters'

In [ ]:
ms3

In [ ]:
df = pd.DataFrame({
    'strana':['dubai','russia','dania','ukraine'],
    'kolvo':[17,143,9,4],
    's':[10,0,1,1]
    }, index=['db','ru','da','uk'])
df

In [ ]:
df.index = ['db','ru','da','uk']

In [ ]:
df.index.name = 'Code'
df

In [ ]:
df['strana']

In [ ]:
df.loc['db']

In [ ]:
df.iloc[0]

In [ ]:
df[df.kolvo >10][['strana','s']]

In [ ]:
df.reset_index()

In [ ]:
df['denis']= df['kolvo']/df['s']*1000000

In [ ]:
df

In [ ]:
df.drop(['denis'],axis='columns')

In [ ]:
t_df= pd.read_csv('titanic.csv')
print(t_df.head())

In [ ]:
print(t_df.groupby(['Sex','Survived'])['PassengerId'].count())

In [ ]:
print(t_df.groupby(['Pclass','Survived'])['PassengerId'].count())

In [ ]:
pass_data = pd.read_csv('titanic.csv')

In [ ]:
pass_data.head(5)


In [ ]:
pass_data.columns

In [ ]:
pass_data[2:5]

In [ ]:
pass_data.iloc[1:5, 1:3]

In [ ]:
pass_data['Name'].head()

In [ ]:
pass_data[['Name','Sex','Parch']].head()

In [ ]:
pass_data[pass_data['Sex']=='female'].head()

In [ ]:
pass_data[(pass_data['Sex'] == 'female')&(pass_data)['Age']>=60 | (pass_data['Sex']=='male')].head()

In [ ]:
pass_data[(pass_data.Sex == 'female')&
            (pass_data.Age > 18)&
            (pass_data.Age < 25)&
            (pass_data.SibSp == 0)&
            (pass_data.Parch == 0)].shape

In [ ]:
pass_data.Age.hist(bins =30)

In [ ]:
pass_data.rename(columns={'Sex':'Sex'}, inplace = True)

In [ ]:
pass_data.head()

In [ ]:
pass_data['Last_name'] = pass_data['Name'].apply(lambda name: name.split(',')[0]).head()
pass_data[['Name', 'Last_name']].head()

In [ ]:
pass_data.drop('Last_name',axis =1 ,inplace=True)

In [ ]:
pass_data.head()

In [ ]:
pass_data['Cabin'].isnull().head()

In [ ]:
pass_data[pass_data['Cabin'].notnull()].head()

In [ ]:
pass_data.sort_values(by=['Pclass','Fare'], ascending=True).head()

In [ ]:
pass_data.sort_values(by=['Pclass','Fare'], ascending=[True,False]).head()

In [ ]:
pass_data.groupby('Sex')

In [ ]:
pass_data.groupby('Sex')['Pclass'].value_counts()

In [ ]:
pass_data.groupby('Pclass')['Fare'].describe()

In [ ]:
pass_data.groupby('Sex')['Age'].mean()

In [ ]:
pass_data.groupby('Sex')['Survived'].mean()

In [ ]:
pass_data.groupby('Pclass')['Survived'].mean()

In [ ]:
pass_data.groupby('Sex', as_index=False)['Survived'].mean()
